name: visual (PR) — disabled
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Visual regression is disabled on CI"


