name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Next build cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: next-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('tsconfig.json') }}-${{ hashFiles('next.config.*', 'next.config/**/*', '**/*.tsx', '**/*.ts') }}
          restore-keys: |
            next-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            next-${{ runner.os }}-
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        env:
          NEXT_PUBLIC_BASE_URL: https://lexatlas.com
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: lexatlas.com
          STRIPE_SECRET_KEY: sk_test_dummy
        run: npm run build --if-present
      - name: Bundle size (Size Limit)
        run: npm run size

  e2e:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers (chromium + system deps)
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:3000
        run: npm run test:e2e

  analyze:
    name: Bundle analyzer report
    runs-on: ubuntu-latest
    needs: ci
    continue-on-error: true
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers (chromium + system deps)
        run: npx playwright install --with-deps chromium
      - name: Build with analyzer
        run: |
          ANALYZE=true npm run build
          tar -czf bundle-analyzer-report.tgz .next/analyze || true
      - uses: actions/upload-artifact@v4
        with:
          name: bundle-analyzer-report
          path: bundle-analyzer-report.tgz

  # Visual regression disabled on CI. Keep e2e only.

  prod-checks:
    name: Production headers/robots checks
    runs-on: ubuntu-latest
    needs: ci
    if: always()
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers (chromium + system deps)
        run: npx playwright install --with-deps chromium
      - name: Build app
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_URL: https://lexatlas.com
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: lexatlas.com
          STRIPE_SECRET_KEY: sk_test_dummy
        run: npm run build
      - name: Start app and run prod header/robots tests
        env:
          NODE_ENV: production
        run: |
          npx kill-port 3000 || true
          (npm start & echo $! > .next_pid) &
          npx wait-on http://127.0.0.1:3000 --timeout 180000
          BASE_URL=http://127.0.0.1:3000 npx playwright test -g "@prod-headers-robots"
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-prod-checks
          path: |
            test-results/**
            playwright-report/**
          retention-days: 7
      - if: always()
        run: |
          if [ -f .next_pid ]; then kill -9 "$(cat .next_pid)" || true; rm -f .next_pid; fi
