name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        env:
          NEXT_PUBLIC_BASE_URL: https://lexatlas.com
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: lexatlas.com
          STRIPE_SECRET_KEY: sk_test_dummy
        run: npm run build --if-present
      - name: Install Playwright (chromium)
        run: npx playwright install --with-deps chromium
      - name: E2E (@smoke on PR, full on push)
        env:
          BASE_URL: http://127.0.0.1:3000
          NEXT_PUBLIC_BASE_URL: http://127.0.0.1:3000
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: localhost
        run: |
          npx next start -H 127.0.0.1 -p 3000 & echo $! > .next_pid
          npx wait-on http://127.0.0.1:3000 --timeout 180000
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npm run test:e2e -- --reporter=list --grep @smoke
          else
            npm run test:e2e -- --reporter=list
          fi
          kill -9 $(cat .next_pid) || true
          rm -f .next_pid
