name: e2e (20.11.1)

on:
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_URL: https://lexatlas.com
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: lexatlas.com
          STRIPE_SECRET_KEY: sk_test_dummy
        run: npm run build
      - name: Install Playwright (chromium)
        run: npx playwright install --with-deps chromium
      - name: Start Next (prod) & wait
        run: |
          trap 'if [ -f .next_pid ]; then kill -9 "$(cat .next_pid)" || true; rm -f .next_pid; fi' EXIT
          (npx next start --hostname 127.0.0.1 --port 3000 & echo $! > .next_pid)
          npx wait-on tcp:127.0.0.1:3000 --timeout 300000
      - name: Run E2E (exclude VR)
        env:
          BASE_URL: http://127.0.0.1:3000
        run: |
          if npm run | grep -q "test:e2e"; then
            timeout 10m npm run test:e2e || { echo "E2E exceeded 10m"; exit 1; }
          else
            timeout 10m npx playwright test --grep-invert @vr || { echo "E2E exceeded 10m"; exit 1; }
          fi
      - name: Stop Next
        if: always()
        run: |
          if [ -f .next_pid ]; then kill -9 "$(cat .next_pid)" || true; rm -f .next_pid; fi


