name: lighthouse

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build Next
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING: '1'
        run: npm run build
      - name: Kill port 3000 if busy
        run: |
          if lsof -i:3000 -t >/dev/null 2>&1; then
            kill -9 $(lsof -i:3000 -t) || true
          fi
      - name: Run Lighthouse CI
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
          SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING: '1'
          # Make Chrome stable in CI
          LHCI_COLLECT_SETTINGS_CHROME_FLAGS: "--no-sandbox --disable-dev-shm-usage --ignore-certificate-errors --allow-insecure-localhost"
        run: npm run lighthouse:ci


