name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: lexatlas-website
          monorepo-tags: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

