name: "Semgrep"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep (OSS rules)
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/javascript
            p/typescript
          generateSarif: true
      - name: Upload SARIF
        if: ${{ !github.event.repository.private }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif


