name: uptime
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        url:
          - "https://lexatlas.com/"
          - "https://lexatlas.com/kits/fra-can"
    steps:
      - name: Curl ${{ matrix.url }}
        run: |
          set -euo pipefail
          URL="${{ matrix.url }}"
          OUT=$(curl -SsfL \
            --retry 5 --retry-all-errors --retry-delay 2 --max-time 15 \
            --connect-timeout 5 \
            -w "status=%{http_code} time=%{time_total}\n" \
            -o /dev/null \
            "$URL")
          echo "$OUT"
          STATUS=$(echo "$OUT" | awk '{print $1}' | cut -d= -f2)
          TIME=$(echo "$OUT" | awk '{print $2}' | cut -d= -f2)
          if [ "$STATUS" -ge 400 ]; then
            echo "❌ HTTP error: $STATUS for $URL"
            exit 1
          fi
          echo "✅ OK: $URL (status=$STATUS, time=${TIME}s)"

