name: Visual Regression — disabled

on:
  pull_request:
  push:
    branches:
      - main
      - fix/vr-baselines

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Visual regression is disabled on CI"


