name: Visual Regression

on:
  pull_request:
  push:
    branches:
      - chore/prod-headers-robots-sitemap

jobs:
  vr:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          (npx kill-port 3000 || true)
          (npm start & echo $! > .next_pid)

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:3000 --timeout 180000

      - name: Install Playwright browsers (Chromium only)
        run: npx playwright install --with-deps chromium

      - name: Run visual regression (compare)
        env:
          BASE_URL: http://127.0.0.1:3000
        run: |
          npx playwright test tests/visual.spec.ts -g @vr

      - name: Upload VR results (artifact)
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-vr-results
          path: |
            playwright-report
            test-results
          if-no-files-found: ignore
          retention-days: 7

      - name: Stop server
        if: always()
        run: |
          (kill -9 $(cat .next_pid) || true) && rm -f .next_pid


